### PR TITLE
Fix property name only for data links

### LINKED ISSUE #150: Couple issues with the terraform data_links( couldn't get the property name in the UI ) after successful plan and apply.
Could get the property name in the UI for the below code or for any of the code, It could get the property value even showing us in the terraform plan and also apply.

resource "signalfx_data_link" "mydatalink_overview_1" {
  context_dashboard_id = "${signalfx_dashboard.overview.id}"
  property_name = "AWSUniqueId"
  target_signalfx_dashboard {
    is_default = true
    name = "Overview awsuniqueid to host dashboard"
    dashboard_group_id = "${signalfx_dashboard_group.xyz_dashboard_group.id}"
    dashboard_id = "${signalfx_dashboard.host.id}"
  }
}

Screen Shot 2020-02-21 at 9 47 27 AM
Screen Shot 2020-02-21 at 9 47 42 AM
Screen Shot 2020-02-21 at 9 48 14 AM

### PR DESCRIPTION
**Pull request by ghost**
property_name was not being set for datalinks if property_value was missing.

Also property_name is required for dashboard targets.

Fixes #150, #151

### CODE REVIEW

File: signalfx/resource_signalfx_data_link.go [hunk 1]
```diff
@@ -161,11 +161,19 @@ func getPayloadDataLink(d *schema.ResourceData) (*datalink.CreateUpdateDataLinkR
...
+	if name, ok := d.GetOk("property_name"); ok {
+		dataLink.PropertyName = name.(string)
+	}
+
 	if val, ok := d.GetOk("context_dashboard_id"); ok {
 		dataLink.ContextId = val.(string)
 	}
 
 	if val, ok := d.GetOk("target_signalfx_dashboard"); ok {
+		if name, ok := d.GetOk("property_name"); !ok || name.(string) == "" {
```
Comment (ghost) [inline signalfx/resource_signalfx_data_link.go]: Do we need to strip name before doing a whitespace comparison? Or is checking for == "" not even needed?

File: signalfx/resource_signalfx_data_link.go [hunk 2]
```diff
@@ -161,11 +161,19 @@ func getPayloadDataLink(d *schema.ResourceData) (*datalink.CreateUpdateDataLinkR
 		}
 	}
 
+	if name, ok := d.GetOk("property_name"); ok {
```
Comment (cory-signalfx) [inline signalfx/resource_signalfx_data_link.go]: I feel this can be simplified by putting this above the check for property value. Something like:

```
if name, ok := d.GetOk("property_name"); ok {
	dataLink.PropertyName = name.(string)
}
if val, ok := d.GetOk("property_value"); ok {
	if dataLink.PropertyName == "" {
		return dataLink, fmt.Errorf("Must supply a property_name when supplying a property_value")
        }
	dataLink.PropertyValue = val.(string)
}
```

This way we're not setting `propertyName` in two places and the logic easily allows only a name, or a value and a name.

File: signalfx/resource_signalfx_data_link.go (hunk 1 above)
Comment (cory-signalfx) [reply signalfx/resource_signalfx_data_link.go]: Wait, is it a thing that property name is required for links to dashboards, but not the other types?!

File: signalfx/resource_signalfx_data_link.go (hunk 2 above)
Comment (cory-signalfx) [reply signalfx/resource_signalfx_data_link.go]: Also, the [docs](https://developers.signalfx.com/datalinks_reference.html#tag/Create-Data-Link) say `propertyName` is required? Should we change ours from `Optional` to `Required`?

**Review by cory-signalfx — CHANGES_REQUESTED** [review]

**Comment by cory-signalfx** [comment]
This is also the problem behind #151, fwict.

File: signalfx/resource_signalfx_data_link.go (hunk 1 above)
Comment (ghost) [reply signalfx/resource_signalfx_data_link.go]: Digging into the code I see that GetOk already checks if it's a zero value. So I guess the == "" isn't needed unless extra whitespace is a concern. But maybe TF handles this higher up in the stack so that whitespace only gets normalized to empty string?

Comment (ghost) [reply signalfx/resource_signalfx_data_link.go]: Yep. I discovered this in the UI. If you click through the different data link types you'll see the trigger options are different for the different types. Only dashboard targets require a property name best I can tell.

Comment (cory-signalfx) [reply signalfx/resource_signalfx_data_link.go]: Fascinating!

Ok, will look over this with that in mind.

File: signalfx/resource_signalfx_data_link.go (hunk 2 above)
Comment (cory-signalfx) [reply signalfx/resource_signalfx_data_link.go]: Strike the required thing above, I see it's Complicated™.

File: signalfx/resource_signalfx_data_link.go (hunk 1 above)
Comment (cory-signalfx) [reply signalfx/resource_signalfx_data_link.go]: Ok, I would just look at `dataLink.PropertyName` in the above code, since you've already verified it there. Also, we should probably make a DOCS ticket that asks to clarify this since I don't think this is explained in the API docs.

**Review by cory-signalfx — CHANGES_REQUESTED** [review]

File: signalfx/resource_signalfx_data_link.go (hunk 1 above)
Comment (ghost) [reply signalfx/resource_signalfx_data_link.go]: https://signalfuse.atlassian.net/browse/DOCS-1143

**Review by cory-signalfx — APPROVED** [review]
Yay! Merge away!
