### PR TITLE
Delete AWS integration when the resource_signalfx_aws_integration is destroyed

### LINKED ISSUE #388: AWS integrations removal with metricstreams is not working
When trying to remove AWS integration which has metricstreams enabled it fails. See following output

Plan: 0 to add, 0 to change, 2 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.splunk_apm_eu_north_1.signalfx_aws_integration.aws_myteam: Destroying... [id=FTgZvMGAAAA]
module.splunk_apm_eu_north_1.signalfx_aws_integration.aws_myteam: Destruction complete after 0s
module.splunk_apm_eu_north_1.signalfx_aws_external_integration.aws_myteam_extern: Destroying... [id=FTgZvMGAAAA]
module.splunk_apm_eu_north_1.signalfx_aws_external_integration.aws_myteam_extern: Still destroying... [id=FTgZvMGAAAA, 10s elapsed]
module.splunk_apm_eu_north_1.signalfx_aws_external_integration.aws_myteam_extern: Still destroying... [id=FTgZvMGAAAA, 20s elapsed]
module.splunk_apm_eu_north_1.signalfx_aws_external_integration.aws_myteam_extern: Still destroying... [id=FTgZvMGAAAA, 30s elapsed]
module.splunk_apm_eu_north_1.signalfx_aws_external_integration.aws_myteam_extern: Still destroying... [id=FTgZvMGAAAA, 40s elapsed]
module.splunk_apm_eu_north_1.signalfx_aws_external_integration.aws_myteam_extern: Still destroying... [id=FTgZvMGAAAA, 50s elapsed]
module.splunk_apm_eu_north_1.signalfx_aws_external_integration.aws_myteam_extern: Still destroying... [id=FTgZvMGAAAA, 1m0s elapsed]
module.splunk_apm_eu_north_1.signalfx_aws_external_integration.aws_myteam_extern: Still destroying... [id=FTgZvMGAAAA, 1m10s elapsed]
module.splunk_apm_eu_north_1.signalfx_aws_external_integration.aws_myteam_extern: Still destroying... [id=FTgZvMGAAAA, 1m20s elapsed]
module.splunk_apm_eu_north_1.signalfx_aws_external_integration.aws_myteam_extern: Still destroying... [id=FTgZvMGAAAA, 1m30s elapsed]
module.splunk_apm_eu_north_1.signalfx_aws_external_integration.aws_myteam_extern: Still destroying... [id=FTgZvMGAAAA, 1m40s elapsed]
module.splunk_apm_eu_north_1.signalfx_aws_external_integration.aws_myteam_extern: Still destroying... [id=FTgZvMGAAAA, 1m50s elapsed]
module.splunk_apm_eu_north_1.signalfx_aws_external_integration.aws_myteam_extern: Still destroying... [id=FTgZvMGAAAA, 2m0s elapsed]
╷
│ Error: Error waiting for integration FTgZvMGAAAA state for use_metric_streams_sync to become disabled: unexpected state 'CANCELLATION_FAILED', wanted target ', DISABLED'. last error: %!s(<nil>)
│

### PR DESCRIPTION
**Pull request by bgola-signalfx**
Fixes [!388](https://github.com/splunk-terraform/terraform-provider-signalfx/issues/388)

### CODE REVIEW

**Comment by bgola-signalfx** [comment]
I have read the CLA Document and I hereby sign the CLA

File: signalfx/resource_signalfx_aws_integration.go [hunk 1]
```diff
@@ -749,12 +757,15 @@ func waitForIntegrationSpecificSyncStateToSettle(d *schema.ResourceData, syncSta
...
+func integrationAWSDelete(d *schema.ResourceData, meta any) error {
+	return DoIntegrationAWSDelete(d, meta)
+}
+
+func noop(_ *schema.ResourceData, _ any) error {
 	return nil
 }
 
-func validateFilterAction(v interface{}, k string) (we []string, errors []error) {
+func validateFilterAction(v any, _ string) (we []string, errors []error) {
```
Comment (anosek-an) [inline signalfx/resource_signalfx_aws_integration.go:768]: can we remove the second param?

File: signalfx/resource_signalfx_aws_integration.go [hunk 2]
```diff
@@ -667,13 +670,18 @@ func integrationAWSUpdate(d *schema.ResourceData, meta interface{}) error {
...
+func DoIntegrationAWSDelete(d *schema.ResourceData, meta any) error {
 	config := meta.(*signalfxConfig)
 
 	// Retrieve current integration state
 	int, err := config.Client.GetAWSCloudWatchIntegration(context.TODO(), d.Id())
 	if err != nil {
-		return fmt.Errorf("Error fetching existing integration %s, %s", d.Id(), err.Error())
+		var re *signalfx.ResponseError
+		if errors.As(err, &re) && re.Code() == http.StatusNotFound {
+			// integration already deleted, bail out
```
Comment (anosek-an) [inline signalfx/resource_signalfx_aws_integration.go]: nit: debug log on 404

**Review by anosek-an — APPROVED** [review]

File: signalfx/resource_signalfx_aws_integration.go (hunk 1 above)
Comment (bgola-signalfx) [reply signalfx/resource_signalfx_aws_integration.go:768]: I don't think so as this function has to match the TF's `SchemaValidateFunc` signature. 

Without the second param there's this error:
`Cannot use 'validateFilterAction' (type func(v any) (we []string, errors []error)) as the type SchemaValidateFunc`

File: signalfx/resource_signalfx_aws_integration.go (hunk 2 above)
Comment (bgola-signalfx) [reply signalfx/resource_signalfx_aws_integration.go]: added

File: signalfx/resource_signalfx_aws_integration.go (hunk 1 above)
Comment (anosek-an) [reply signalfx/resource_signalfx_aws_integration.go:768]: we can consider replacing it at some point

https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#SchemaValidateFunc
